[package]
name = "suspend"
version = "0.1.0"
authors = ["Michal Hornický <mhornick@redhat.com>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "*"
syn = { version =  "1.0.5", features = ["full", "visit"] }
quote = "1.0.2"